import React from 'react'
import {
  useUserMachine,
  UserMachineAction,
  UserMachineState,
} from '../states/user.machine'

export const Home: React.FC = () => {
  const [state, send] = useUserMachine()

  function login() {
    send({
      type: UserMachineAction.LOGIN,
      user: 'mockUser',
      password: 'password',
    })
  }

  function logout() {
    send({ type: UserMachineAction.LOGOUT })
  }

  return (
    <>
      <h1>Redux + TypeScript {state.name}</h1>
      <p>
        Hello {state.context.name} and welcome! :) This app was generated by the
        Create React App template and bootstrapped with Redux, React Router,
        TypeScript, ESlint, Prettier for you. Take a look around ;)
      </p>
      {state.name !== UserMachineState.LOGGED_IN && (
        <button
          type="button"
          className="btn"
          disabled={state.name === UserMachineState.LOADING}
          onClick={() => login()}
        >
          Login
        </button>
      )}
      {state.name === UserMachineState.LOGGED_IN && (
        <button type="button" className="btn" onClick={() => logout()}>
          Logout
        </button>
      )}
    </>
  )
}
